name: build

on:
  push:
    branches:    
      - build
jobs:
  build:

    env:
      APP_NAME: soapy-sdr
      GHC_VER: 8.6.5
      CABAL_VER: 3.2
      APPIMGTOOL_VER: 12
      LIQUIDDSP_VER: 1.3.2
      LIBRTLSDR_VER: 0.6.0
      SOAPYRTLSDR_VER: 0.3.0
      BUILD_TYPE: Debug

    runs-on: ubuntu-16.04

    steps:

    - name: Prepare
      run: |
        sudo apt-get update
        sudo apt-get install libsndfile1-dev libusb-1.0-0-dev libfftw3-dev cabal-install-$CABAL_VER ghc-$GHC_VER
        wget -P ~/bin https://github.com/AppImage/AppImageKit/releases/download/$APPIMGTOOL_VER/appimagetool-x86_64.AppImage
        chmod +x ~/bin/appimagetool-x86_64.AppImage
        git clone https://github.com/pothosware/SoapySDR.git
        cd SoapySDR
        git checkout f722f9ce5b629c3c44401a9bf628b3f8e67a9695
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
        make -j
        sudo make install
        cd ../..
        wget https://github.com/steve-m/librtlsdr/archive/$LIBRTLSDR_VER.tar.gz
        tar -zxvf $LIBRTLSDR_VER.tar.gz
        cd librtlsdr-$LIBRTLSDR_VER
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
        make -j
        sudo make install
        cd ../..
        wget https://github.com/pothosware/SoapyRTLSDR/archive/soapy-rtlsdr-$SOAPYRTLSDR_VER.tar.gz
        tar -zxvf  soapy-rtlsdr-$SOAPYRTLSDR_VER.tar.gz
        cd SoapyRTLSDR-soapy-rtlsdr-$SOAPYRTLSDR_VER
        mkdir build
        cd build
        cmake -DCMAKE_BUILD_TYPE=$BUILD_TYPE ..
        make -j
        sudo make install
        cd ../..
        wget https://github.com/jgaeddert/liquid-dsp/archive/v$LIQUIDDSP_VER.tar.gz
        tar -zxvf v$LIQUIDDSP_VER.tar.gz
        cd liquid-dsp-$LIQUIDDSP_VER
        ./bootstrap.sh
        ./configure
        make -j4
        sudo make install
        sudo ldconfig
    
    - name: Checkout
      uses: actions/checkout@01aecccf739ca6ff86c0539fbc67a7a5007bbc81
      
    - name: Build
      run: |
        export PATH=$PATH:/opt/cabal/bin
        export PATH=$PATH:~/bin
        cabal update
        cabal v2-configure -w /opt/ghc/$GHC_VER/bin/ghc-$GHC_VER
        cabal user-config update
        cabal v2-build --enable-relocatable
        cabal v2-install --enable-relocatable
        sudo updatedb
        cabal v2-run cabal2appimage
        appimagetool-x86_64.AppImage -vn soapy-sdr.AppDir
        ./Soapy_SDR-x86_64.AppImage -h

    - uses: actions/upload-artifact@e7eefc491732c06d0ebbf4d4f49dcc25b4d2f3a8
      with:
        name: Soapy_SDR-x86_64.AppImage
        path: Soapy_SDR-x86_64.AppImage

